export const translations = {
  ar: {
    title: "لوحة الحجوزات الذكية",
    welcome: "مرحباً",
    logout: "خروج",
    totalReservations: "إجمالي الحجوزات",
    confirmedReservations: "حجوزات مؤكدة",
    pendingReservations: "في الانتظار",
    cancelledReservations: "حجوزات ملغاة",
    totalEarnings: "إجمالي الإيرادات",
    searchPlaceholder: "ابحث باسم العميل...",
    allReservations: "كل الحجوزات",
    confirmed: "مؤكدة",
    pending: "في الانتظار",
    completed: "مكتملة",
    cancelled: "ملغاة",
    addBtn: "إضافة حجز جديد",
    noData: "لا توجد حجوزات تطابق بحثك الحالي.",
    resId: "رقم الحجز",
    custName: "اسم العميل",
    service: "الخدمة / الصالة",
    dateTime: "التاريخ والوقت",
    price: "السعر",
    status: "الحالة",
    actions: "إجراءات",
    currency: "ج.م",
    loginTitle: "تسجيل الدخول للنظام",
    usernamePlaceholder: "اسم المستخدم",
    passwordPlaceholder: "كلمة المرور",
    loginBtn: "دخول",
    loginError: "اسم المستخدم أو كلمة المرور غير صحيحة!",
  },
  en: {
    title: "Smart Booking Dashboard",
    welcome: "Welcome",
    logout: "Logout",
    totalReservations: "Total Reservations",
    confirmedReservations: "Confirmed",
    pendingReservations: "Pending",
    cancelledReservations: "Cancelled",
    totalEarnings: "Total Earnings",
    searchPlaceholder: "Search customer name...",
    allReservations: "All Reservations",
    confirmed: "Confirmed",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    addBtn: "Add New Reservation",
    noData: "No reservations match your current search.",
    resId: "ID",
    custName: "Customer Name",
    service: "Service / Hall",
    dateTime: "Date & Time",
    price: "Price",
    status: "Status",
    actions: "Actions",
    currency: "EGP",
    loginTitle: "System Login",
    usernamePlaceholder: "Username",
    passwordPlaceholder: "Password",
    loginBtn: "Login",
    loginError: "Invalid username or password!",
  },
};
