export const initialReservations = [
  {
    id: "RES-101",
    customerName: "أحمد محمد",
    service: "حجز VIP - صالة 1",
    date: "2026-06-18",
    time: "06:00 م",
    status: "confirmed",
    price: 150,
  },
  {
    id: "RES-102",
    customerName: "سارة أمين",
    service: "حجز عائلي - صالة 3",
    date: "2026-06-19",
    time: "09:00 م",
    status: "pending",
    price: 300,
  },
  {
    id: "RES-103",
    customerName: "محمود حسن",
    service: "تذكرة عادية - صالة 2",
    date: "2026-06-18",
    time: "04:30 م",
    status: "completed",
    price: 80,
  },
  {
    id: "RES-104",
    customerName: "دينا علي",
    service: "حجز VIP - صالة 1",
    date: "2026-06-20",
    time: "11:00 م",
    status: "cancelled",
    price: 150,
  },
  {
    id: "RES-105",
    customerName: "عمر خالد",
    service: "تذكرة عادية - صالة 2",
    date: "2026-06-22",
    time: "01:00 م",
    status: "confirmed",
    price: 80,
  },
];
